Chore

diff --git a/pkgs/git-wrapped/git-wrapped b/pkgs/git-wrapped/git-wrapped
--- a/pkgs/git-wrapped/git-wrapped
+++ b/pkgs/git-wrapped/git-wrapped
@@ -2,28 +2,28 @@
 
 git='%%GIT%%/bin/git'
 
-if [ "$1" = "restore" ]; then
-    staged=false
-    for arg in "$@"; do
-        [ "$arg" = "--staged" ] && staged=true && break
-    done
+# if [ "$1" = "restore" ]; then
+#     staged=false
+#     for arg in "$@"; do
+#         [ "$arg" = "--staged" ] && staged=true && break
+#     done
 
-    if [ "$staged" = false ]; then
-        echo "Checking for uncommitted changes..."
-        if ! $git diff --quiet; then
-            echo "Backing up current diff (stash copy, keep working tree)..."
-            if $git stash push -m "auto-pre-restore" --keep-index >/dev/null 2>&1; then
-                $git stash apply 'stash@{0}' >/dev/null 2>&1 || {
-                    echo "Warning: failed to re-apply stash." >&2
-                }
-                echo "Diff safely copied to stash and working tree preserved."
-            else
-                echo "Error: stash failed. Aborting restore." >&2
-                exit 1
-            fi
-        fi
-    fi
-fi
+#     if [ "$staged" = false ]; then
+#         echo "Checking for uncommitted changes..."
+#         if ! $git diff --quiet; then
+#             echo "Backing up current diff (stash copy, keep working tree)..."
+#             if $git stash push -m "auto-pre-restore" --keep-index >/dev/null 2>&1; then
+#                 $git stash apply 'stash@{0}' >/dev/null 2>&1 || {
+#                     echo "Warning: failed to re-apply stash." >&2
+#                 }
+#                 echo "Diff safely copied to stash and working tree preserved."
+#             else
+#                 echo "Error: stash failed. Aborting restore." >&2
+#                 exit 1
+#             fi
+#         fi
+#     fi
+# fi
 
 if [ "$1" = "reset" ] && [ "$2" = "--hard" ]; then
     if ! $git diff --quiet || ! $git diff --cached --quiet; then
